name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: hosting201883.a2f36.netcup.net
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftp
          server-dir: /test/
          timeout: 120
          security: "false"  # Explizit unverschlüsselt
