name: Lint and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  deploy:
    name: Deploy over FTP
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy over FTP
        run: |
          lftp -e "set ssl:verify-certificate no; open -u ${{ secrets.FTPUSERNAME }},${{ secrets.FTPPASSWORD }} ftp://hosting201883.a2f36.netcup.net; mirror -R --exclude .github/ ./ /test/; bye"
