name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over FTP
        uses: lukaszraczylo/ftp-deploy@v1.0.0
        with:
          ftp-server: ftp://hosting201883.a2f36.netcup.net
          ftp-username: ${{ secrets.FTPUSERNAME }}
          ftp-password: ${{ secrets.FTPPASSWORD }}
          local-dir: .
          server-dir: /test/
          log-level: verbose
          dry-run: false
